project:
  render:
  - slides.qmd
  output-dir: dist
title: "Modelo SIR"
subtitle: "Simulando uma epidemia usando Matemática e Computação"
author:
  - Breno Pinna
  - João A. Proença
date: last-modified
lang: pt-br
date-format: long
documentclass: beamer
format:
  beamer:
    pdf-engine: pdflatex
    slide-level: 3
    theme: Madrid
    toc: true
    toc-title: "Sumário"
    fig-height: 5.3
    latex-min-runs: 3
  ipynb:
    output-file: notebook.ipynb
include-in-header: preamble.tex
